baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Shakhawat's Blog"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = "2"
[[menu.main]]
URL = "https://www.shakhawat.me/"
name = "About Me"
weight = "3"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "https://www.youtube.com/shakhawat/"
name = "YouTube"
weight = 5
[[menu.main]]
URL = "https://linux.shakhawat.me"
name = "হাতেকলমে লিনাক্স"
weight = "6"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Shakhawat"
description = ""
[params.banner]
heading = "Hello! I'm SHAKHAWAT HOSSAIN"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "a passionate Security Researcher, Creator, and Technology Enthusiast."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Pabna, Bangladesh<br>www.shakhawat.me<br>mail@shakhawat.me"
enable = true
title = "Want To Connect With Me? Ok Let's Talk!"
[params.footer]
address = "Pabna 6660, Bangladesh"
content = "... is the best place to learn and practice hacking in ethical way. Learn about IT security with some tips and tricks including various OSes."
copyright = "&copy; ALL RIGHTS RESERVED. [<u>BY SHAKHAWAT HOSSAIN</u>](https://www.shakhawat.me)."
hours = "Null"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "mail@shakhawat.me"
facebook = "https://www.facebook.com/shakhawat.pi"
instagram = "https://www.instagram.com/shakhawat.pi"
linkedin = "https://www.linkedin.com/in/shakhawat-pi"
twitter = "https://www.twitter.com/shakhawat_me"
yelp = "https://www.github.com/shakhawat-pi"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
